# _config.yml

# Site settings
title: "Giabbi's Writeups"
description: "A curated collection of my CTF challenges and writeups."
theme: jekyll-theme-hacker

# Deployment settings for GitHub Pages
baseurl: "/" 
url: "https://giabbiswriteups.com" 

# Markdown processor
markdown: kramdown

kramdown:
  auto_ids: true

plugins:
  - jekyll-seo-tag

# Permalink style for cleaner URLs
permalink: pretty
