# _config.yml

# Site settings
title: "Giabbi's Writeups"
description: "It's not cheating if you just take a peek!"
theme: jekyll-theme-hacker

# Deployment settings for GitHub Pages
baseurl: "/" 
url: "https://giabbiswriteups.com" 

# Markdown processor
markdown: kramdown

kramdown:
  auto_ids: true

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Permalink style for cleaner URLs
permalink: pretty

collections:
  writeups:
    output: true
    permalink: /writeups/:path/

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock

